baseURL                          = "https://eks.news/"   # Your domain name. Must end with "/"
theme                            = "introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
title                            = "EKS News"
enableEmoji = true
enableRobotsTXT = true
ignoreErrors = ["error-disable-taxonomy"]

[params]
    themeStyle                   = "light"                  # Choose "light" or "dark" or "auto"
    favicon                      = "favicon.ico"          # Path to favicon file
    showRSSButton                = true                   # Show rss button in navigation
    fadeIn                       = false                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "2006-01-02"

    # Configure the home page
    [params.home]
        introHeight              = "medium"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = true                    # show all posts in an archive format
        numberOfProjectsToShow   = 0                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = false                    # Show your current local time in contact section
        timeZone                 = "America/Detroit"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "en-US"                 # Language specific format to use
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = false
        facebook                 = false
        pinterest                = false

    # To enable giscus, the GitHub-discussions-based comment section,
    # input the repository for the discussions below. For more details, see
    # https://www.joelnitta.com/posts/2021-11-24_using-giscus/
    # and https://github.com/giscus/giscus
    [params.giscus]
        # repo = "github-user/github-repo" # Entering repo will enable giscus
        repo-id = "enter-repo-id"
        category = "Comments"
        category-id = "enter-category-id"
        mapping = "pathname"
        reactions-enabled = "0"
        emit-metadata = "0"
        theme = "light"
        lang = "en"

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://twitter.com/awscloud"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"
#    [[params.social]]
#        url   = "https://facebook.com/"
#        icon  = "facebook-f" # icon name without the 'fa-'
#        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.linkedin.com/company/amazon-web-services"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://github.com/aws/eks-news"
        icon  = "github" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.reddit.com/r/aws/"
        icon  = "reddit" # icon name without the 'fa-'
        icon_pack = "fab"
#    [[params.social]]
#        url = "mailto:youremail@email.com"  # For a direct email link, use "mailto:test@example.org".
#        icon = "paper-plane" # icon name without the 'fa-'
#        icon_pack = "fas"
#    [[params.social]]
#        url   = "https://mastodon.social/"
#        icon  = "mastodon" # icon name without the 'fa-'
#        icon_pack = "fab"
#        html_attributes = "rel=\"me\"" # Add rel attribute for Mastodon profile link verification


# If you don't want to use the default menu, you can define one by yourself
[[menu.main]]
  name    = "Home"
  url     = "/"
  weight  = 0
[[menu.main]]
  name    = "Subscribe"
  url     = "/#subscribe"
  weight  = 10
[[menu.main]]
  name    = "Archives"
  url     = "/archives/"
  weight  = 20
[[menu.main]]
  name    = "About"
  url     = "/#about"
  weight  = 30
[[menu.main]]
  name    = "Contact"
  url     = "/#contact"
  weight  = 40

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    # noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style = "solarized-dark"
    tabWidth = 4

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "EKS News"
        [languages.en.params]
            description  = "EKS News: The latest and greatest on all things AWS Elastic Kubernetes Service, Kubernetes, and Cloud Native"   # Max 160 characters show in search results
            footerText   = "This newsletter is curated by Amazon Web Services (AWS) employees"                      # Text to override default footer text (markdown allowed)

#    [languages.es]
#        languageName     = "Español"
#        languageCode     = "es"
#        contentDir       = "content/es"
#        weight           = 1
#        title            = "Introducción"
#        [languages.es.params]
#            description  = "Descripcion del sitio web"
#            # footerText   = ""

#    [languages.de]
#        languageName     = "Deutsch"
#        languageCode     = "de"
#        contentDir       = "content/de"
#        weight           = 2
#        title            = "Vorstellung"
#        [languages.de.params]
#            dateFormat   = "2. January 2006"
#            description  = "Beschreibung der Webseite"
#            # footerText   = ""

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true