---
name: Scheduled Netlify site build
on:
  schedule:
  - cron: '0 7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger build on Netlify
      env:
        TOKEN: ${{ secrets.NETLIFY_BUILD_HOOK_KEY }}
      run: >-
          curl -s -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d "{}" "https://api.netlify.com/build_hooks/${TOKEN}"
